<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => 'd65e5d259331e6d58d9c42b410473312',
  'DATABASE_URL' => 'mysql://root:@127.0.0.1:3306/ticketing',
  'MAILER_URL' => 'null://localhost',
);
